"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var p1 = new point_1.Point(5.3, 2.1);
p1.toString();
var point1 = new point_1.Point(1, 2);
console.log(point1.toString());
var point0 = new point_1.Point(2, 6);
console.log(point0.distanceTolOrigin());
var etX = new point_1.Point(5, 7);
var etY = new point_1.Point(3, 9);
console.log(etX.calculateDistance(etY));
