"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var point1 = new point_1.Point(1, 2);
console.log(point1.toString());
var point0 = new point_1.Point(2, 6);
console.log(point0.distanceTolOrigin());
var etX = new point_1.Point(5, 7);
var etY = new point_1.Point(3, 9);
console.log(etX.calculateDistance(etY));
var cuadrant1 = new point_1.Point(1, 2);
console.log(cuadrant1.calcularQuadrant());
var pointA = new point_1.Point(2, 3);
var pointB = new point_1.Point(3, 4);
var pointC = new point_1.Point(5, 8);
var listPoints = [pointA, pointB, pointC];
var currentPoint = new point_1.Point(7, 5);
console.log(currentPoint.calculateNearest(listPoints));
